// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personapi_dotnet.Models.Entities;

#nullable disable

namespace personapi_dotnet.Migrations
{
    [DbContext(typeof(persona_dbContext))]
    [Migration("20221017003504_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Estudio", b =>
                {
                    b.Property<int>("IdProf")
                        .HasColumnType("int")
                        .HasColumnName("id_prof");

                    b.Property<int>("CcPer")
                        .HasColumnType("int")
                        .HasColumnName("cc_per");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Univer")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("univer");

                    b.HasKey("IdProf", "CcPer")
                        .HasName("PK__Estudios__FB3F71A60D66D208");

                    b.HasIndex("CcPer");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Persona", b =>
                {
                    b.Property<int>("Cc")
                        .HasColumnType("int")
                        .HasColumnName("cc");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("apellido");

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("genero")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.HasKey("Cc")
                        .HasName("PK__Persona__3213666D7BB192F1");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Profesion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Dest")
                        .HasColumnType("text")
                        .HasColumnName("dest");

                    b.Property<string>("Nom")
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("Profesion", (string)null);
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Telefono", b =>
                {
                    b.Property<string>("Num")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("num");

                    b.Property<int>("Duenio")
                        .HasColumnType("int")
                        .HasColumnName("duenio");

                    b.Property<string>("Oper")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("oper");

                    b.HasKey("Num", "Duenio")
                        .HasName("PK__Telefono__1EE0396B24860D5B");

                    b.HasIndex("Duenio");

                    b.ToTable("Telefono", (string)null);
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Estudio", b =>
                {
                    b.HasOne("personapi_dotnet.Models.Entities.Persona", "CcPerNavigation")
                        .WithMany("Estudios")
                        .HasForeignKey("CcPer")
                        .IsRequired()
                        .HasConstraintName("FK__Estudios__cc_per__2B3F6F97");

                    b.HasOne("personapi_dotnet.Models.Entities.Profesion", "IdProfNavigation")
                        .WithMany("Estudios")
                        .HasForeignKey("IdProf")
                        .IsRequired()
                        .HasConstraintName("FK__Estudios__id_pro__2A4B4B5E");

                    b.Navigation("CcPerNavigation");

                    b.Navigation("IdProfNavigation");
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Telefono", b =>
                {
                    b.HasOne("personapi_dotnet.Models.Entities.Persona", "DuenioNavigation")
                        .WithMany("Telefonos")
                        .HasForeignKey("Duenio")
                        .IsRequired()
                        .HasConstraintName("FK__Telefono__duenio__2E1BDC42");

                    b.Navigation("DuenioNavigation");
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Persona", b =>
                {
                    b.Navigation("Estudios");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("personapi_dotnet.Models.Entities.Profesion", b =>
                {
                    b.Navigation("Estudios");
                });
#pragma warning restore 612, 618
        }
    }
}
